# Default values for chryspy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: captaingab/chrispyimg
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: cedbc2f32aa7dd321a9186fc80a2406feb91293a
containerPort: 80
targetPort: 80

service:
  type: LoadBalancer
  port: 80