apiVersion: apps/v1
kind: Deployment
metadata:
  name: chryspyapp
  labels: 
    app: chryspyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chryspyapp
  template:
    metadata:
      labels:
        app: chryspyapp
    spec:
      containers:
      - name: chryspyapp
        image: captaingab/chrispyimg:captaingab/chrispyimg:c69673c589100a387bd710730ed690db9585ae70
        ports:
        - name: chryspyimg-port
          containerPort: 80