apiVersion: apps/v1
kind: Deployment
metadata:
  name: chryspyapp
  labels: 
    app: chryspyapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chryspyapp
  template:
    metadata:
      labels:
        app: chryspyapp
    spec:
      containers:
      - name: chryspyapp
        image: captaingab/chrispyimg:18dda6a5706feb0fd17f5ff1bf7f1f9b45a0b1ec
        ports:
        - name: chryspyimg-port
          containerPort: 80
      
       
