# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chryspyapp-chart.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort }}  
  selector:
    {{- include "chryspyapp-chart.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
